language: generic
dist: focal
arch: amd64

# Do not change line endings when checking out code for windows jobs
git:
  autocrlf: input

# Travis-ci bugs prevent completion. A workaround is to disable secret filtering
# In early 2018 said they are working on fixing their filter script, and in 10/2019
# they were still working on it.
filter_secrets: false

_aliases:
  - &docker
    os: linux
    services: docker
    before_script:
      - docker pull souffle/ubuntu:focal-base
      - docker run -d -t --name souf -w /souffle --mount src="$(pwd)",target=/souffle,type=bind souffle/ubuntu:focal-base /bin/sh
    after_script: docker container stop souf
    after_failure: docker exec souf /bin/sh -c ".travis/after_failure.sh"
  - &osxgcc
    os: osx
    osx_image: xcode11.3
    install: ". .travis/osx/install_withgcc.sh"
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
    after_failure: ".travis/after_failure.sh"
  - &osxclang
    <<: *osxgcc
    install: ". .travis/osx/install.sh"
    compiler: clang
    language: cpp

stages:
  - Warmup
  - Testing
  - Packaging

jobs:
  allow_failures:
    - name: "Debian arm64 package"
  fast_finish: true
  include:
# Style check stage
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 1indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 2indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 3indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 4indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 5indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 6indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 7indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 8indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 9indows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 10ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 11ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 12ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 13ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 14ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 15ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 16ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 17ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
# MSVC souffle-interface
  - stage: Testing
    os: windows
    language: cpp
    name: 18ndows WSL interface without OMP
    before_script: '.travis/init-windows-test.sh'
    script: '.travis/windows-test.sh'
